swagger: '2.0'
info:
  version: 0.0.1
  title: SAM Swagger Example
  description: SAM Swagger Example API
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
paths:
  '/v1/test':
    get:
      x-amazon-apigateway-request-validator: all
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: aws_proxy
        uri:
          'Fn::Sub': >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetTestFunction.Arn}/invocations
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/TestItem'
definitions:
  TestItem:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  
